"""Async REST client for Tavily.

Auto-generated by HackForge AgentIntegrator on 2026-02-28.
"""
from __future__ import annotations

from typing import Any
import httpx


class TavilyClient:
    BASE_URL = ""

    def __init__(self, api_key: str, base_url: str = "", timeout: int = 30) -> None:
        self._api_key = api_key
        self._base_url = base_url or self.BASE_URL
        self._timeout = timeout
        self._http: httpx.AsyncClient | None = None

    async def _ensure(self) -> None:
        if self._http is None:
            self._http = httpx.AsyncClient(
                base_url=self._base_url,
                timeout=self._timeout,
                headers={
                    "Authorization": f"{self._api_key}",
                    "Content-Type": "application/json",
                },
            )

    async def close(self) -> None:
        if self._http:
            await self._http.aclose()
            self._http = None

    async def request(
        self, method: str, path: str, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        await self._ensure()
        assert self._http is not None
        params = params or {}
        if method.upper() in ("GET", "DELETE"):
            resp = await self._http.request(method, path, params=params)
        else:
            resp = await self._http.request(method, path, json=params)
        resp.raise_for_status()
        return resp.json()
