"""MCP Server for Tavily.

Auto-generated by HackForge AgentIntegrator on 2026-02-28.
"""
from __future__ import annotations

import os
from mcp.server.fastmcp import FastMCP
from client import TavilyClient

mcp = FastMCP(
    name="Tavily MCP",
    version="0.1.0",
    description="Tavily API integration",
)

_client: TavilyClient | None = None


@mcp.startup()
async def _startup() -> None:
    global _client
    api_key = os.environ.get("TAVILY_API_KEY", "")
    if not api_key:
        raise RuntimeError("TAVILY_API_KEY not set")
    _client = TavilyClient(api_key=api_key)


@mcp.shutdown()
async def _shutdown() -> None:
    if _client:
        await _client.close()


@mcp.tool()
async def ping() -> dict:
    """Health check — verify the API key works."""
    assert _client is not None
    return await _client.request("GET", "/")


@mcp.tool()
async def search(query: str) -> dict:
    """Search or query the Tavily API."""
    assert _client is not None
    return await _client.request("POST", "/search", {"query": query})


if __name__ == "__main__":
    mcp.run()
